# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.94</version>
#    <timestamp>2026-06-17T17:35:09.272Z</timestamp>
#    <hash>b15a1caa2b17072b</hash>
# </meta>

neoforge:
  - "/^neoforge$/m"
fabric:
  - "/^fabric$/m"
forge:
  - "/^forge$/m"

1.21.x:
  - "/^1.21$/m"
1.20.x:
  - "/^1.20$/m"
1.19.x:
  - "/^1.19$/m"
1.18.x:
  - "/^1.18$/m"
