# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>0.0.0-dev</version>
#    <timestamp>2026-03-07T18:24:53.505Z</timestamp>
# </meta>

neoforge:
  - "neoforge"
fabric:
  - "fabric"
forge:
  - "forge"

1.21.x:
  - "1.21"
1.20.x:
  - "1.20"
1.19.x:
  - "1.19"
1.18.x:
  - "1.18"
