org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.caching=true
kotlin.code.style=official

mc_version=1.21.1
neoforge_version=21.1.219
parchment_mappings_version=2024.11.17

mod_id=sliceanddice
mod_version=0.0.0-dev
release_type=release
mod_name=Create Slice & Dice
mod_author=possible_triangle
mod_description=Making automation for Farmers Delight more sensible
maven_group=com.possible-triangle

kotlin_forge_version=5.11.0

repository=pssbletrngle/sliceanddice
modrinth_project_id=GmjmRQ0A
curseforge_project_id=659674
