kotlin.code.style=official
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mc_version=1.20.1
fabric_api_version=0.92.6+1.20.1
fabric_loader_version=0.17.2

mod_id=sliceanddice
mod_version=0.0.0-dev
release_type=beta
mod_name=Create Slice & Dice
mod_author=possible_triangle
maven_group=com.possible-triangle

kotlin_fabric_version=1.13.3+kotlin.2.1.21

repository=pssbletrngle/sliceanddice
modrinth_project_id=GmjmRQ0A
curseforge_project_id=659674
