org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.caching=true
kotlin.code.style=official

mc_version=1.21.1
neoforge_version=21.1.213
java_version=21

mod_id=sliceanddice
mod_version=0.0.0-dev
release_type=release
mod_name=Create Slice & Dice
mod_author=possible_triangle
maven_group=com.possible-triangle

jei_version=19.21.0.247
flywheel_version=1.0.2
create_version=6.0.7-159
ponder_version=1.0.63
registrate_version=MC1.21-1.3.0+67
kotlin_forge_version=5.8.0

farmers_delight_version=opCbq7uB
create_enchantment_industry_version=p8KnWGu6
vegan_delight_version=lJlxcthS
#blueprint_version=6.1.0
#neapolitan_version=4023083
#overweight_farming_version=4395450
configured_version=5873784
catalog_version=6926815
#cofh_core_version=3838025
#thermal_foundation_version=3837827
#thermal_expansion_version=3837868
#thermal_cultivation_version=3837822

repository=pssbletrngle/sliceanddice
modrinth_project_id=GmjmRQ0A
curseforge_project_id=659674
