modLoader = "kotlinforforge"
loaderVersion = "[5,)"
license = "https://github.com/${repository}/blob/main/1.21.x/LICENSE.md"
issueTrackerURL = "https://github.com/${repository}/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
logoFile = "assets/${mod_id}/icon.png"
description = "${mod_description}"
updateJSONURL="https://api.modrinth.com/updates/slice-and-dice/forge_updates.json?neoforge=only"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${mc_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId="kotlinforforge"
    versionRange="[5.8,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="atmosphere"
    versionRange="[1.0.7,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId = "create"
    versionRange = "[6.0.9,7.0.0)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "create_enchantment_industry"
    versionRange = "[1.3.0,)"
    ordering = "NONE"
    side = "BOTH"
    type = "optional"

[[mixins]]
    config="${mod_id}.mixins.json"
