[versions]
jei = "19.27.0.340"
create-simulated = "1.2.1"
atmosphere = "1.0.13"

[libraries]
registrate = { group = "com.tterrag.registrate", name = "Registrate", version = "MC1.21-1.3.0+67" }
create = { group = "com.simibubi.create", name = "create-1.21.1", version = "6.0.10-281" }
ponder = { group = "net.createmod.ponder", name = "ponder-neoforge", version = "1.0.82+mc1.21.1" }
flywheel = { group = "dev.engine-room.flywheel", name = "flywheel-neoforge-1.21.1", version = "1.0.6" }

sable = { group = "dev.ryanhcode.sable", name = "sable-neoforge-1.21.1", version = "1.2.2" }
sable-companion = { group = "dev.ryanhcode.sable-companion", name = "sable-companion-common-1.21.1", version = "1.6.0" }
create-simulated = { group = "dev.simulated_team.simulated", name = "simulated-neoforge-1.21.1", version.ref = "create-simulated" }
create-aeronautics = { group = "dev.eriksonn.aeronautics", name = "aeronautics-neoforge-1.21.1", version.ref = "create-simulated" }

atmosphere = { group = "com.possible-triangle", name = "atmosphere-1.21.1-neoforge", version.ref = "atmosphere" }
atmosphere-api = { group = "com.possible-triangle", name = "atmosphere-1.21.1-api", version.ref = "atmosphere" }

jei-common-api = { group = "mezz.jei", name = "jei-1.21.1-common-api", version.ref = "jei" }
jei-neoforge-api = { group = "mezz.jei", name = "jei-1.21.1-neoforge-api", version.ref = "jei" }
jei-neoforge = { group = "mezz.jei", name = "jei-1.21.1-neoforge", version.ref = "jei" }

oreganized = { "group" = "dev.galena", name = "oreganized", version = "5.2.0-SNAPSHOT" }
