# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.94</version>
#    <timestamp>2026-06-17T17:35:09.272Z</timestamp>
#    <hash>9d521ee415ea61ee</hash>
# </meta>

blank_issues_enabled: false
