# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.120</version>
#    <timestamp>2026-08-11T16:30:39.617Z</timestamp>
#    <hash>9d521ee415ea61ee</hash>
# </meta>

blank_issues_enabled: false
