# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.95</version>
#    <timestamp>2026-06-21T19:14:49.562Z</timestamp>
#    <hash>9d521ee415ea61ee</hash>
# </meta>

blank_issues_enabled: false
