name = "slice-and-dice"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "058ac00e65ae7bdd69a0928fab76079ebeed4413bd7eeadbdc9a05f5ad294f9e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
