name = "slice-and-dice"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8109de5525f7aa392a38a21e5d2cd36eeaddf90acb8f9597b78387c98067bc9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
