# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.94</version>
#    <timestamp>2026-06-17T17:35:09.272Z</timestamp>
#    <hash>d1e9f9e741782d1e</hash>
# </meta>

name: "Issue Labeler"

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.4
        with:
          configuration-path: .github/labeler.yml
          enable-versioned-regex: 0
          repo-token: ${{ github.token }}
