# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.94</version>
#    <timestamp>2026-06-17T17:35:09.272Z</timestamp>
#    <hash>d5ba0f0d510fcb71</hash>
# </meta>

name: Test

on:
  workflow_dispatch:

  pull_request:
    types: [opened, synchronize]

  push:
    branches:
      - "main"
      - "main/**"

env:
  CI: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v5
        with:
          java-version: 26
          distribution: temurin

      - uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: ${{ github.event_name != 'push' }}
          dependency-graph: generate-and-submit

      - name: Cache SonarQube packages
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - uses: PssbleTrngle/find-release@v1
        if: ${{ github.event_name != 'pull_request' }}
        id: action
        with:
          type: draft
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: ./gradlew build check --stacktrace
        env:
          RELEASE_VERSION: ${{ steps.action.outputs.tag }}

      - name: Analyze
        if: ${{ github.event_name != 'pull_request' }}
        run: ./gradlew sonar
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          GITHUB_DEPENDENCY_GRAPH_ENABLED: false

      - name: Publish -SNAPSHOT version
        if: ${{ fromJSON(steps.action.outputs.matched) }}
        run: ./gradlew publish
        continue-on-error: true
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_TOKEN: ${{ secrets.NEXUS_TOKEN }}
          RELEASE_VERSION: ${{ steps.action.outputs.tag }}
          SNAPSHOT: true
