# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.55</version>
#    <timestamp>2026-05-06T18:08:18.277Z</timestamp>
#    <hash>f14bde545df6c0b2</hash>
# </meta>

name: Test

on:
  workflow_dispatch:
    inputs:
      upload:
        description: "Upload Artifact"
        default: false
        required: true
        type: boolean

  pull_request:
    types: [opened, synchronize]

  push:
    branches:
      - "main"
      - "main/**"

env:
  CI: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.event_name != 'push' }}
          dependency-graph: generate-and-submit

      - name: Cache SonarQube packages
        if: ${{ github.event_name == 'push' }}
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Test
        run: ./gradlew build check

      - name: Analyze
        if: ${{ github.event_name == 'push' }}
        run: ./gradlew sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          GITHUB_DEPENDENCY_GRAPH_ENABLED: false

      - uses: actions/upload-artifact@v4
        if: ${{ inputs.upload }}
        with:
          name: build
          path: "**/build/libs/*.jar"
